In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_with_target_comp.csv')

In [3]:
df.head()

,Unnamed: 0,speaker,text,type,election_year,date,candidate,result
0,0,John Kennedy,I uh – said that Ive served this country for f...,Pres,1960.0,1960-10-21,1.0,1
1,1,John Kennedy,"Mr. Howe, Mr. Vice President. First uh – let m...",Pres,1960.0,1960-10-21,1.0,1
2,2,Richard Nixon,"Mr. Howe, Senator Kennedy, my fellow Americans...",Pres,1960.0,1960-10-21,1.0,0
3,3,John Kennedy,"Good evening, Mr. Howe.",Pres,1960.0,1960-10-21,1.0,1
4,4,Richard Nixon,"Good evening, Mr. Howe.",Pres,1960.0,1960-10-21,1.0,0

In [4]:
df = df.drop('Unnamed: 0', 1)

In [5]:
df.head()

,speaker,text,type,election_year,date,candidate,result
0,John Kennedy,I uh – said that Ive served this country for f...,Pres,1960.0,1960-10-21,1.0,1
1,John Kennedy,"Mr. Howe, Mr. Vice President. First uh – let m...",Pres,1960.0,1960-10-21,1.0,1
2,Richard Nixon,"Mr. Howe, Senator Kennedy, my fellow Americans...",Pres,1960.0,1960-10-21,1.0,0
3,John Kennedy,"Good evening, Mr. Howe.",Pres,1960.0,1960-10-21,1.0,1
4,Richard Nixon,"Good evening, Mr. Howe.",Pres,1960.0,1960-10-21,1.0,0

In [6]:
df['party']='U'

In [7]:
df.head()

,speaker,text,type,election_year,date,candidate,result,party
0,John Kennedy,I uh – said that Ive served this country for f...,Pres,1960.0,1960-10-21,1.0,1,U
1,John Kennedy,"Mr. Howe, Mr. Vice President. First uh – let m...",Pres,1960.0,1960-10-21,1.0,1,U
2,Richard Nixon,"Mr. Howe, Senator Kennedy, my fellow Americans...",Pres,1960.0,1960-10-21,1.0,0,U
3,John Kennedy,"Good evening, Mr. Howe.",Pres,1960.0,1960-10-21,1.0,1,U
4,Richard Nixon,"Good evening, Mr. Howe.",Pres,1960.0,1960-10-21,1.0,0,U

In [11]:
df.speaker.unique()

array(['John Kennedy', 'Richard Nixon', 'Gerald Ford', 'Jimmy Carter',
       'Ronald Reagan', 'Walter Mondale', 'George H. W. Bush',
       'Geraldine Ferraro', 'Michael Dukakis', 'Dan Quayle',
       'Lloyd Bentsen', 'Bill Clinton', 'Ross Perot', 'Al Gore',
       'James Stockdale', 'Jack Kemp', 'Bob Dole', 'George W. Bush',
       'Joe Lieberman', 'Dick Cheney', 'John Edwards', 'John Kerry',
       'Barack Obama', 'John McCain', 'Paul Ryan', 'Joe Biden',
       'Mitt Romney', 'Herman Cain', 'Jon Huntsman', 'Rick Perry',
       'Rick Santorum', 'Newt Gingrich', 'Gary Johnson', 'Ron Paul',
       'John Kasich', 'Chris Christie', 'Rand Paul', 'Jeb Bush',
       'Marco Rubio', 'Ted Cruz', 'Ben Carson', 'Donald Trump',
       'Carly Fiorina', 'Scott Walker', 'Mike Huckabee', 'Mike Pence',
       'Hillary Clinton', 'Tim Kaine', 'Bernie Sanders',
       "Martin O'Malley", 'Jim Webb', 'Lincoln Chafee', 'Amy Klobuchar',
       'Elizabeth Warren', 'Michael Bloomberg', 'Pete Buttigieg',
       'Tom Steyer', 'Kamala Harris', 'Tulsi Gabbard', 'Cory Booker',
       'Jay Inslee', 'Andrew Yang', 'Kirsten Gillibrand', 'Julian Castro',
       'Bill DeBlasio', "Beto O'Rourke", 'John Hickenlooper', 'Tim Ryan',
       'John Delaney', 'Marianne Williamson', 'Steve Bullock',
       'Eric Swalwell', 'Michael Bennett'], dtype=object)